# Tarea - PC1
Importar librerías y subir archivo .csv

In [1]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/SALINASSebas/geocomputacion_-1GEO20-/refs/heads/main/tarea_PC1/datos.csv"

df = pd.read_csv(url)
df.head()

,CÓDIGO,Día,1968,1969,1970,1971,1972,1973,1974,1975,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,PROM. TOTAL
0,1,1,NaN,17.8,19.0,17.1,18.2,20.8,16.8,17.4,...,NaN,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.243478
1,1,2,NaN,18.5,19.2,16.5,19.0,20.9,17.4,19.8,...,NaN,18.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.180851
2,1,3,NaN,17.4,19.8,16.8,18.0,21.2,16.0,17.4,...,NaN,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.251064
3,1,4,NaN,18.9,20.3,17.0,19.3,21.3,17.7,18.0,...,19.5,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.418750
4,1,5,NaN,17.8,19.9,17.5,18.0,21.3,17.7,19.0,...,21.6,18.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.483333

### Pregunta 1:
Renombrar la columna "CÓDIGO" por "mes" y eliminar la columna "PROM. TOTAL"

In [2]:
# Para renombrar la columna "CÓDIGO" se usará el comando .rename y se le asignará el nuevo nombre a la columna por medio de un diccionario

df = df.rename(columns = {"CÓDIGO":"mes","Día":"dia"})

# Confirmamos que se ha renombrado la columna "CÓDIGO" del dataframe
df.head()

,mes,dia,1968,1969,1970,1971,1972,1973,1974,1975,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,PROM. TOTAL
0,1,1,NaN,17.8,19.0,17.1,18.2,20.8,16.8,17.4,...,NaN,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.243478
1,1,2,NaN,18.5,19.2,16.5,19.0,20.9,17.4,19.8,...,NaN,18.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.180851
2,1,3,NaN,17.4,19.8,16.8,18.0,21.2,16.0,17.4,...,NaN,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.251064
3,1,4,NaN,18.9,20.3,17.0,19.3,21.3,17.7,18.0,...,19.5,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.418750
4,1,5,NaN,17.8,19.9,17.5,18.0,21.3,17.7,19.0,...,21.6,18.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.483333

In [3]:
# Para eliminar la columna "PROM. TOTAL" se actualizará el dataframe abarcando solo los datos de las columnas deseadas mediante el comando .iloc

df = df.loc[:,"mes":"2024"]

# Confirmamos que ya no se encuentra la columna "PROM. TOTAL" en las columnas del dataframe
df.head()

,mes,dia,1968,1969,1970,1971,1972,1973,1974,1975,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,1,1,NaN,17.8,19.0,17.1,18.2,20.8,16.8,17.4,...,18.2,NaN,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2,NaN,18.5,19.2,16.5,19.0,20.9,17.4,19.8,...,19.4,NaN,18.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,NaN,17.4,19.8,16.8,18.0,21.2,16.0,17.4,...,18.6,NaN,18.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,4,NaN,18.9,20.3,17.0,19.3,21.3,17.7,18.0,...,18.8,19.5,19.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,5,NaN,17.8,19.9,17.5,18.0,21.3,17.7,19.0,...,19.4,21.6,18.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Pregunta 2:
Reestructurar la tabla para tener una fila por fecha real (con esto se debe eliminar los 29/02 de los años no bisiestos)

In [4]:
# Se recolectaron los datos del dataframe dentro de una variable separada 
df_datos = df.loc[:,"1968":"2024"]

# Se crea un dataframe dentro de una variable nueva para que recopile los datos del siguiente proceso
df_nuevo = pd.DataFrame(columns=["a","b","c"])

# Con un proceso iterativo for, se recolectan los datos de mes, día y la data del año correspondiente a la columna respectova del df_datos. El nombre de las columnas del dataframe es actualizado en cada iteración para coincidir con el año de cada iteración. Se usa .concat() para apilar los datos de cada año en una sola columna consecutiva
for column in df_datos.columns:
    df_nuevo.columns = df.loc[:,["mes","dia",column]].columns
    df_nuevo = pd.concat([df_nuevo,df.loc[:,["mes","dia",column]]],sort=False)

# Las columna se renombra pues queda como el último año de data recopilada
df_nuevo = df_nuevo.rename(columns={"2024":"data"})
df_nuevo

    mes dia data
0     1   1  NaN
1     1   2  NaN
2     1   3  NaN
3     1   4  NaN
4     1   5  NaN
..   ..  ..  ...
361  12  27  NaN
362  12  28  NaN
363  12  29  NaN
364  12  30  NaN
365  12  31  NaN

[20862 rows x 3 columns]

In [5]:
# El index del proceso de concatenado vuelve a 0 luego de completar la data de cada año. Se usa esto para definir una nueva lista que recopile el año de cada dato registrado
lista_año = []
año_inicio = 1968
for i in df_nuevo.index:
    lista_año.append(año_inicio)
    if i==365:
        año_inicio+=1

# Se agrega una nueva columna de año y se registran los datos de la lista creada
df_nuevo["año"] = lista_año

In [6]:
# Se renombran las columnas y se visualizan los datos
df_nuevo = df_nuevo.rename(columns={"año":"year","mes":"month","dia":"day"})

df_nuevo.head()

  month day data  year
0     1   1  NaN  1968
1     1   2  NaN  1968
2     1   3  NaN  1968
3     1   4  NaN  1968
4     1   5  NaN  1968

In [7]:
# Para eliminar las fechas inexistentes (29 de febrero en años no bisiestos) se transformará el formato de dato de las columnas "month", "day" y "year" a formato "datetime". Primero se crea un df nuevo con la información cronológica de cada dato.
df_fecha = df_nuevo.loc[:,["year","month","day"]]

# Se transforman los datos de las fechas "month" y "day" a tipo "int" para su posterior procesamiento
df_fecha["month"] = df_fecha["month"].astype(int)
df_fecha["day"] = df_fecha["day"].astype(int)

# El df_fecha_final guarda los datos transformados por el comando pd.to_datetime. Este recoge la data de las columnas "month", "day" y "year" y las reemplaza. El argumento "errors = coerce" permite que el comando guarde las fechas inexistentes como NaT.
df_fecha_final = pd.to_datetime(df_fecha, errors = "coerce")
df_fecha_final.head()

0   1968-01-01
1   1968-01-02
2   1968-01-03
3   1968-01-04
4   1968-01-05
dtype: datetime64[us]

In [8]:
# Se crea una nueva columna para la fecha y se seleccionan los datos del dataframe df_fecha_final
df_nuevo["date"] = df_fecha_final
df_nuevo.head()

  month day data  year       date
0     1   1  NaN  1968 1968-01-01
1     1   2  NaN  1968 1968-01-02
2     1   3  NaN  1968 1968-01-03
3     1   4  NaN  1968 1968-01-04
4     1   5  NaN  1968 1968-01-05

In [9]:
# Se eliminan las filas con fechas inexistentes con el comando .dropna en la columna "date" (toma los datos NaT generados)
df_nuevo = df_nuevo.dropna(subset=["date"])

# Se eliminan las columnas "month", "day" y "year"
df_nuevo = df_nuevo.loc[:,["date","data"]]

# Se resetea el índice del dataframe para una mejor identificación de elementos
df_nuevo = df_nuevo.reset_index(drop=True)

# Se corrige el tipo de dato de la columna "data"
df_nuevo["data"] = df_nuevo["data"].astype(float)

df_nuevo

            date  data
0     1968-01-01   NaN
1     1968-01-02   NaN
2     1968-01-03   NaN
3     1968-01-04   NaN
4     1968-01-05   NaN
...          ...   ...
20815 2024-12-27   NaN
20816 2024-12-28   NaN
20817 2024-12-29   NaN
20818 2024-12-30   NaN
20819 2024-12-31   NaN

[20820 rows x 2 columns]

### Pregunta 3
Identificar qué valores son NaN originalmente y cuáles están fuera del rango físico aceptable, guardando esa información en dos nuevas columnas: "es_dato_faltante" y "es_dato_corregido" (formato booleano, True/False)

In [10]:
# La columna "es_dato_faltante" se crea como resultado del comando .isna() aplicado en la columna "data". El comando devuelve un set de valores "True" y "False" si el valor del elemento de la columna "data" es NaN o no, respectivamente (PASO REALIZADO CON AYUDA DE IA)
df_nuevo["es_dato_faltante"] = df_nuevo["data"].isna()

# La columna "es_dato_corregido" se crea tomando valores "False" bajo el supuesto de que ningún dato ha sido modificado
df_nuevo["es_dato_corregido"] = False

df_nuevo.head()

        date  data  es_dato_faltante  es_dato_corregido
0 1968-01-01   NaN              True              False
1 1968-01-02   NaN              True              False
2 1968-01-03   NaN              True              False
3 1968-01-04   NaN              True              False
4 1968-01-05   NaN              True              False

### Pregunta 4
Reemplazar los valores fuera de rango por NaN.

In [11]:
# Los comandos "max" y "min" permiten ver los valores máximos y mínimos del set de datos de la columna "data". Se usa el comando .dropna() para no incluir los valores NaN dentro del comando "max" y "min"
print(max(df_nuevo["data"].dropna()))
print(min(df_nuevo["data"].dropna()))

218.0
11.0

In [12]:
# Debido a que una temperatura de 218.0 para representar el clima no presenta sentido físico, se identifica como el dato que debe ser reemplazado. Para eso, se determina la ubicación del dato en el dataframe.
df_nuevo.loc[df_nuevo["data"]==218]

            date   data  es_dato_faltante  es_dato_corregido
17606 2016-03-15  218.0             False              False

In [13]:
# El dato es reemplazado con el comando .replace() a un valor nulo (NaN)
df_nuevo = df_nuevo.replace(218,np.nan)

# Luego de haber procesado el dato fuera de rango, se vuelve a identificar el valor máximo de la columna "data"
print(max(df_nuevo["data"].dropna()))

28.9

In [14]:
# Debido a que el valor fuera de rango ha sido corregido, se registra la modificación en la columna "es_dato_corregido"
df_nuevo.loc[17606,"es_dato_corregido"] = True

df_nuevo.loc[17606,:]

date                 2016-03-15 00:00:00
data                                 NaN
es_dato_faltante                   False
es_dato_corregido                   True
Name: 17606, dtype: object

### Pregunta 5
Agregar la columna "variable" (la variable debe estar en formato texto: str, sin espacios ni tildes)

In [15]:
# Se crea una nueva columna que refleje la variable analizada en el dataframe (temperatura mínima). Esta debe estar en formato "str"
df_nuevo["variable"] = "tmin"

df_nuevo.info()

<class 'pandas.DataFrame'>
RangeIndex: 20820 entries, 0 to 20819
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   date               20820 non-null  datetime64[us]
 1   data               18048 non-null  float64
 2   es_dato_faltante   20820 non-null  bool
 3   es_dato_corregido  20820 non-null  bool
 4   variable           20820 non-null  str
dtypes: bool(2), datetime64[us](1), float64(1), str(1)
memory usage: 612.6 KB

## Exportar
Exportar el dataframe modificado como archivo .csv

In [159]:
# Finalmente, se guarda el dataframe modificado en un archivo .csv con el comando .to_csv. El atributo "index = False" se usa para no guardar el índice como columna en el archivo .csv.
df_nuevo.to_csv('tmin_corregido_Sebastian.csv', index=False)